import { Category, Product, SubCategory } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'c1', name: 'Para Él' },
  { id: 'c2', name: 'Para Ella' },
  { id: 'c3', name: 'Unisex' },
];

export const INITIAL_SUBCATEGORIES: SubCategory[] = [
  { id: 's1', categoryId: 'c1', name: 'Amaderado' },
  { id: 's2', categoryId: 'c1', name: 'Cítrico' },
  { id: 's3', categoryId: 'c2', name: 'Floral' },
  { id: 's4', categoryId: 'c2', name: 'Frutal' },
  { id: 's5', categoryId: 'c3', name: 'Oriental' },
  { id: 's6', categoryId: 'c3', name: 'Fresco' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Midnight Gentleman',
    brand: 'Balalaika Exclusive',
    description: 'Una fragancia intensa con notas de roble y tabaco, ideal para la noche.',
    price: 89.99,
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop',
    categoryId: 'c1',
    subCategoryId: 's1',
    featured: true,
  },
  {
    id: 'p2',
    name: 'Rose Elixir',
    brand: 'Essence Pure',
    description: 'Esencia pura de rosas búlgaras con un toque de vainilla dulce.',
    price: 75.50,
    imageUrl: 'https://images.unsplash.com/photo-1594035910387-4066d65750e6?q=80&w=1000&auto=format&fit=crop',
    categoryId: 'c2',
    subCategoryId: 's3',
    featured: true,
  },
  {
    id: 'p3',
    name: 'Ocean Breeze',
    brand: 'Aqua',
    description: 'Frescura marina capturada en una botella, perfecto para el uso diario.',
    price: 60.00,
    imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1000&auto=format&fit=crop',
    categoryId: 'c1',
    subCategoryId: 's2',
    featured: false,
  },
  {
    id: 'p4',
    name: 'Golden Amber',
    brand: 'Luxe',
    description: 'Un aroma unisex cálido y envolvente con notas de ámbar y especias.',
    price: 120.00,
    imageUrl: 'https://images.unsplash.com/photo-1519669011783-4eaa95fa1b7d?q=80&w=1000&auto=format&fit=crop',
    categoryId: 'c3',
    subCategoryId: 's5',
    featured: true,
  },
  {
    id: 'p5',
    name: 'Citrus Bloom',
    brand: 'Naturale',
    description: 'Explosión de limón y bergamota con un fondo suave de jazmín.',
    price: 55.00,
    imageUrl: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?q=80&w=1000&auto=format&fit=crop',
    categoryId: 'c2',
    subCategoryId: 's4',
    featured: false,
  },
  {
    id: 'p6',
    name: 'Vetiver Woods',
    brand: 'Balalaika Exclusive',
    description: 'Elegancia atemporal con vetiver de Haití y cedro.',
    price: 95.00,
    imageUrl: 'https://images.unsplash.com/photo-1615361200141-f45040f367be?q=80&w=1000&auto=format&fit=crop',
    categoryId: 'c3',
    subCategoryId: 's1',
    featured: false,
  },
];
